### ISSUE TITLE
关于 nginx 配置文件存放目录的问题

### ISSUE THREAD

**Issue by im-wmkong** [wi1dcard/laravel-deployment#4]
作者您好，关于 nginx 配置文件通过 scp 上传至 sites-enabled 目录下，我觉得应该上传至 sites-available 目录下，然后在 sites-enabled 下创建软连接

**Comment by wi1dcard** [comment]
是的，标准做法应当如此。根据语义可得知：`sites-available` 表示可用的站点，`sites-enabled` 表示启用的站点。使用软链接将「可用站点」链接到「启用站点」，是最符合规范的做法。

不过此处考虑到：

1. 为了减少步骤，尽可能让读者较快地实现目标。
2. 直接上传至 `sites-enabled`，似乎（我暂时还没有想到）并没有什么实质（例如安全方面）上的影响。
3. 由于云时代的发展，如今的单台服务器已经不推荐划分多个虚拟主机（站点）了，所以不会出现「移除」软链接的情况。

因此，我在本文中使用直接 SCP 到 `sites-enabled` 的方式。当然，使用软链接还是最规范的做法～你的想法很棒！

**Comment by im-wmkong** [comment]
谢谢解答
