### ISSUE TITLE
部署代码是不是没有讲migrate

### ISSUE THREAD

**Issue by SimonWang2014** [wi1dcard/laravel-deployment#6]
新项目部署的时候，开发都是在本地，数据库也是，是否可以加入`migrate`？

**Comment by wi1dcard** [comment]
不太理解你的意思，请详细说明。

**Comment by SimonWang2014** [comment]
前两天照着你的做，看到第九章就说部署好了，后面就讲优化了，但是新项目，数据表还没有建，缺少migrate这一步，所以第八章是不是应该提一下migrate。

PS：后面发现在讲优化的时候提了migrate 😂
